[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Handle share links
[[redirects]]
  from = "/l/*"
  to = "/share/index.html"
  status = 200

[[redirects]]
  from = "/share/*"
  to = "/share/index.html"
  status = 200

[[redirects]]
  from = "/lineup*"
  to = "/share/index.html"
  status = 200

# Handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200 
